// AUTOGENERATED FILE
// This file was generated from grammar.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface MemoryDiagramActionDict<T> extends BaseActionDict<T> {
  Diagram_multi?: (this: NonterminalNode, arg0: IterationNode) => T;
  Diagram_single?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Diagram?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  SubDiagram?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: TerminalNode) => T;
  Frames?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  Frame?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  Lines?: (this: NonterminalNode, arg0: IterationNode) => T;
  Line?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Statement?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Allocation?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  heapSymbol?: (this: NonterminalNode, arg0: IterationNode, arg1: TerminalNode) => T;
  Assignment?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  Label?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode) => T;
  Value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Object?: (this: NonterminalNode, arg0: IterationNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: TerminalNode) => T;
  ArrayObject?: (this: NonterminalNode, arg0: IterationNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: TerminalNode) => T;
  ObjectField?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  Array?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  Pointer?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  Location?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  LocationMemberAccess?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  LocationSubscript?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  ArrayString?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  StringLiteral?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  literal?: (this: NonterminalNode, arg0: IterationNode) => T;
  Directive?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  LabelDirective?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  LabelLocation?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  StyleDirective?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  LabelStyle?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: IterationNode) => T;
  NodeStyles?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: NonterminalNode, arg3: IterationNode) => T;
  LinkStyle?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: IterationNode) => T;
  Style?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  LayoutDirective?: (this: NonterminalNode, arg0: TerminalNode, arg1: TerminalNode) => T;
  MultiLocation?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  LocationSlice?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode, arg3: IterationNode, arg4: IterationNode, arg5: IterationNode, arg6: TerminalNode) => T;
  cssClass?: (this: NonterminalNode, arg0: IterationNode) => T;
  identifier?: (this: NonterminalNode, arg0: IterationNode) => T;
  string?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  char?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  nonEscape?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  escape?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  number?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  int?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode) => T;
  float?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: TerminalNode, arg3: IterationNode) => T;
  JsonValue?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  JsonObject?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  JsonArray?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  JsonPair?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  JsonBool?: (this: NonterminalNode, arg0: TerminalNode) => T;
}

export interface MemoryDiagramSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: MemoryDiagramActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: MemoryDiagramActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: MemoryDiagramActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: MemoryDiagramActionDict<T>): this;
}

export interface MemoryDiagramGrammar extends Grammar {
  createSemantics(): MemoryDiagramSemantics;
  extendSemantics(superSemantics: MemoryDiagramSemantics): MemoryDiagramSemantics;
}

declare const grammar: MemoryDiagramGrammar;
export default grammar;

